title: Web Re-Designed
author: Michelle
email: lien.m.pham@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just a site to play around and learn with Github is about.

# social links
twitter_username: miishy4 # DO NOT include the @ character, or else the build will fail!
github_username:  michixlien # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
